'use strict';
var errorCode = {
	DB_PARAMS_INVALID: 0,
	DB_CONNECTION_FAIL: 0,
	DB_QUERY_FAIL: 0,
	DB_INSERT_FAIL: 0,
	DB_UPDATE_FAIL: 0,
	DB_REMOVE_FAIL: 0,
	DB_QUERYCOUNT_FAIL: 0,
	USER_INVALID: 1,//create user
	PARAM_INVALID: 1,
	USER_NOT_EXIST: 2,
	PASSWORD_ERROR: 3,
	USER_LOGINSTATE_EXCEPTION: 2,
	OLD_PASSWORD_ERROR: 1,
	SAME_PASSWORD_ERROR: 2,

	PASSWORD_NOT_CONSTANTS: 2//create user

};

module.exports = errorCode;
