'use strict';
var errorCode = {
	DB_PARAMS_INVALID: 8,
	DB_CONNECTION_FAIL: 8,
	DB_QUERY_FAIL: 8,
	DB_INSERT_FAIL: 8,
	DB_UPDATE_FAIL: 8,
	DB_REMOVE_FAIL: 8,
	DB_QUERYCOUNT_FAIL: 8,
	USER_INVALID: 1, //create user
	PARAM_INVALID: 1,
	USER_NOT_EXIST: 2,
	PASSWORD_ERROR: 3,
	USER_LOGINSTATE_EXCEPTION: 2,
	OLD_PASSWORD_ERROR: 1,
	SAME_PASSWORD_ERROR: 2,
	PASSWORD_NOT_CONSTANTS: 2, //create user

	UPDATE_OLD_PASSWORD_ERROR: 2,
	UPDATE_OLD_NEW_SAME: 3,

	UPLOAD_FORMAT_ERROR: 1,
	UPLOAD_PORTRAIR_ERROR: 2,
	SOCKET_CONNECTION_ERROR: 1,
	BILLING_TIMEOUT: 2,
	SMSCODE_SEND_FAILED: 1,
	SMSCODE_USER_REGISTERED: 2,
	SMSCODE_ERROR: 3
};

module.exports = errorCode;